### ISSUE TITLE
Model download link

### ISSUE THREAD

**Issue by lmagoncalo** [Trunpm/Insightface_EfficientNet#1]
Is it possible to provide the pre-trained model in a platform different from Baidu?

**Comment by Trunpm** [comment]
ok，please paid attention on the code page in the next few days.




| |
min
|
|
邮箱：jamypeng2018@163.com
|

Signature is customized by Netease Mail Master

On 07/02/2020 18:11, lmagoncalo wrote:

Is it possible to provide the pre-trained model in a platform different from Baidu?
